# Generated by Django 5.0.1 on 2024-12-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("employee_id", models.AutoField(primary_key=True, serialize=False)),
                ("company_id", models.CharField(max_length=20)),
                ("first_name", models.CharField(max_length=100)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("last_name", models.CharField(max_length=100)),
                (
                    "sex",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Employee", "Employee"),
                            ("HR", "Human Resources"),
                            ("Admin", "Administrator"),
                        ],
                        default="Employee",
                        max_length=8,
                    ),
                ),
                ("department", models.CharField(max_length=100)),
                ("contact_number", models.CharField(max_length=15)),
                ("date_employed", models.DateField()),
                ("leave_credits", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Employee",
                "verbose_name_plural": "Employees",
                "db_table": "employee_table",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.AddConstraint(
            model_name="employee",
            constraint=models.UniqueConstraint(
                fields=("company_id", "employee_id"), name="unique_company_employee"
            ),
        ),
        migrations.AddConstraint(
            model_name="employee",
            constraint=models.CheckConstraint(
                check=models.Q(("leave_credits__gte", 0)), name="positive_leave_credits"
            ),
        ),
    ]
