# Generated by Django 5.0.1 on 2024-12-27 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="employee",
            name="unique_company_employee",
        ),
    ]
