# Generated by Django 5.0.1 on 2024-12-29 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_employee_unique_company_employee"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monday_start", models.TimeField(blank=True, null=True)),
                ("monday_end", models.TimeField(blank=True, null=True)),
                ("tuesday_start", models.TimeField(blank=True, null=True)),
                ("tuesday_end", models.TimeField(blank=True, null=True)),
                ("wednesday_start", models.TimeField(blank=True, null=True)),
                ("wednesday_end", models.TimeField(blank=True, null=True)),
                ("thursday_start", models.TimeField(blank=True, null=True)),
                ("thursday_end", models.TimeField(blank=True, null=True)),
                ("friday_start", models.TimeField(blank=True, null=True)),
                ("friday_end", models.TimeField(blank=True, null=True)),
                ("saturday_start", models.TimeField(blank=True, null=True)),
                ("saturday_end", models.TimeField(blank=True, null=True)),
                ("sunday_start", models.TimeField(blank=True, null=True)),
                ("sunday_end", models.TimeField(blank=True, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.employee"
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee Schedule",
                "verbose_name_plural": "Employee Schedules",
                "db_table": "employee_schedule_table",
            },
        ),
    ]
