# Generated by Django 5.0.1 on 2024-12-31 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_employeeschedule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeeschedule",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.employee",
                unique=True,
            ),
        ),
    ]
