# Generated by Django 5.1.7 on 2025-05-21 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_leaverequest_department_approval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='leave_credit_deduction',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
