# Generated by Django 5.0.1 on 2025-01-01 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_employeeschedule_employee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeeschedule",
            name="employee",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="core.employee"
            ),
        ),
    ]
