# Generated by Django 5.1.7 on 2025-05-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_leaverequest_leave_credit_deduction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='deduction_applied',
            field=models.BooleanField(default=False),
        ),
    ]
