# Generated by Django 5.1.7 on 2025-05-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_leaverequest_deduction_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='leave_credits2',
            field=models.IntegerField(default=0),
        ),
    ]
