# Generated by Django 5.1.7 on 2025-05-23 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_employee_leave_credits2'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='leave_dates',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('SICK', 'Sick Leave'), ('MATERNITY', 'Maternity Leave'), ('PATERNITY', 'Paternity Leave'), ('VACATION', 'Vacation Leave'), ('EMERGENCY', 'Emergency Leave')], max_length=20),
        ),
    ]
