# Generated by Django 5.1.3 on 2025-01-03 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_employee_linked_account_employee_user_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='linked_account',
        ),
    ]
