# Generated by Django 5.1.7 on 2025-05-23 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_leaverequest_leave_dates_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='end_of_leave',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='start_of_leave',
        ),
    ]
