# Generated by Django 5.0.1 on 2025-02-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_remove_employee_linked_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="company_id",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
