# Generated by Django 5.1.6 on 2025-02-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_employee_company_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('leave_respondents', models.ManyToManyField(blank=True, related_name='leave_departments', to='core.employee')),
                ('shift_respondents', models.ManyToManyField(blank=True, related_name='shift_departments', to='core.employee')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='employees', to='core.department'),
        ),
    ]
