# Generated by Django 5.1.6 on 2025-02-07 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_employee_department_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='department_memberships', to='core.employee'),
        ),
        migrations.AlterField(
            model_name='department',
            name='leave_respondents',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('department_memberships__isnull', False)), related_name='leave_departments', to='core.employee'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(default='Unassigned', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='shift_respondents',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('department_memberships__isnull', False)), related_name='shift_departments', to='core.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='department_employees', to='core.department'),
        ),
    ]
