# Generated by Django 5.0.1 on 2025-05-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_attendance_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendance",
            name="status",
        ),
        migrations.AddField(
            model_name="attendance",
            name="arrival_status",
            field=models.CharField(
                choices=[
                    ("On-Time", "On-Time"),
                    ("Late", "Late"),
                    ("Absent", "Absent"),
                    ("Rest Day", "Rest Day"),
                ],
                default="Absent",
                help_text="Status based on time-in",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="departure_status",
            field=models.CharField(
                choices=[
                    ("On-Time", "On-Time"),
                    ("Undertime", "Undertime"),
                    ("Absent", "Absent"),
                    ("Rest Day", "Rest Day"),
                ],
                default="Absent",
                help_text="Status based on time-out",
                max_length=20,
            ),
        ),
    ]
