# Generated by Django 5.1.6 on 2025-02-07 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_department_employees_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='employees',
        ),
        migrations.RemoveField(
            model_name='department',
            name='leave_respondents',
        ),
        migrations.RemoveField(
            model_name='department',
            name='shift_respondents',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='departments',
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='core.department'),
        ),
        migrations.CreateModel(
            name='DepartmentRespondent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respondents', to='core.department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respondent_roles', to='core.employee')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('department', 'employee'), name='unique_respondent')],
            },
        ),
    ]
