# Generated by Django 5.1.6 on 2025-02-07 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_department_employees_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DepartmentRespondent',
        ),
    ]
