# Generated by Django 5.0.1 on 2025-05-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_remove_attendance_status_attendance_arrival_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="late_minutes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="attendance",
            name="undertime_minutes",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
