# Generated by Django 5.0.1 on 2025-02-07 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_delete_departmentrespondent"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("time_in", models.DateTimeField(blank=True, null=True)),
                ("time_out", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("On-Time", "On-Time"),
                            ("Late", "Late"),
                            ("Absent", "Absent"),
                            ("Rest Day", "Rest Day"),
                        ],
                        default="Absent",
                        max_length=20,
                    ),
                ),
                ("scheduled_start", models.TimeField()),
                ("scheduled_end", models.TimeField()),
                ("is_rest_day", models.BooleanField()),
                ("late_minutes", models.PositiveIntegerField(default=0)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.employee"
                    ),
                ),
            ],
            options={
                "unique_together": {("employee", "date")},
            },
        ),
    ]
