# Generated by Django 5.1.6 on 2025-02-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_delete_departmentrespondent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.AddField(
            model_name='department',
            name='leave_respondents',
            field=models.ManyToManyField(blank=True, related_name='leave_departments', to='core.employee'),
        ),
        migrations.AddField(
            model_name='department',
            name='shift_respondents',
            field=models.ManyToManyField(blank=True, related_name='shift_departments', to='core.employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='employees', to='core.department'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
