# Generated by Django 5.1.6 on 2025-02-07 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_employee_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='departments',
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='core.department'),
        ),
        migrations.AlterField(
            model_name='department',
            name='leave_respondents',
            field=models.ManyToManyField(blank=True, limit_choices_to={'department__isnull': False}, related_name='leave_departments', to='core.employee'),
        ),
        migrations.AlterField(
            model_name='department',
            name='shift_respondents',
            field=models.ManyToManyField(blank=True, limit_choices_to={'department__isnull': False}, related_name='shift_departments', to='core.employee'),
        ),
    ]
