# Generated by Django 5.1.6 on 2025-02-07 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_attendance'),
        ('core', '0016_remove_employee_departments_employee_department_and_more'),
    ]

    operations = [
    ]
